{"name":"newrelic","hostname":"simas","pid":8373,"level":30,"msg":"Starting New Relic for Node.js connection process.","time":"2014-09-07T19:33:19.652Z","v":0}
{"name":"newrelic","hostname":"simas","pid":8373,"component":"new_relic_response","level":30,"msg":"Reporting to: https://rpm.newrelic.com/accounts/705147/applications/3767099","time":"2014-09-07T19:33:25.345Z","v":0}
{"name":"newrelic","hostname":"simas","pid":8373,"component":"collector_api","level":30,"msg":"Connected to collector-127.newrelic.com:443 with agent run ID 1478200937.","time":"2014-09-07T19:33:25.345Z","v":0}
{"name":"newrelic","hostname":"simas","pid":8373,"component":"collector_api","level":50,"err":{"message":"getaddrinfo ENOTFOUND","name":"Error","stack":"Error: getaddrinfo ENOTFOUND\n    at errnoException (dns.js:37:11)\n    at Object.onanswer [as oncomplete] (dns.js:124:16)","code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo"},"msg":"Calling metric_data on New Relic failed unexpectedly. Data will be held until it can be submitted:","time":"2014-09-07T21:03:26.607Z","v":0}
{"name":"newrelic","hostname":"simas","pid":8373,"level":30,"err":{"message":"getaddrinfo ENOTFOUND","name":"Error","stack":"Error: getaddrinfo ENOTFOUND\n    at errnoException (dns.js:37:11)\n    at Object.onanswer [as oncomplete] (dns.js:124:16)","code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo"},"msg":"Error on submission to New Relic (data held for redelivery):","time":"2014-09-07T21:03:26.607Z","v":0}
{"name":"newrelic","hostname":"simas","pid":8373,"component":"collector_api","level":50,"err":{"message":"getaddrinfo ENOTFOUND","name":"Error","stack":"Error: getaddrinfo ENOTFOUND\n    at errnoException (dns.js:37:11)\n    at Object.onanswer [as oncomplete] (dns.js:124:16)","code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo"},"msg":"Calling metric_data on New Relic failed unexpectedly. Data will be held until it can be submitted:","time":"2014-09-07T21:04:26.614Z","v":0}
{"name":"newrelic","hostname":"simas","pid":8373,"level":30,"err":{"message":"getaddrinfo ENOTFOUND","name":"Error","stack":"Error: getaddrinfo ENOTFOUND\n    at errnoException (dns.js:37:11)\n    at Object.onanswer [as oncomplete] (dns.js:124:16)","code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo"},"msg":"Error on submission to New Relic (data held for redelivery):","time":"2014-09-07T21:04:26.615Z","v":0}
{"name":"newrelic","hostname":"simas","pid":8373,"component":"collector_api","level":50,"err":{"message":"connect ETIMEDOUT","name":"Error","stack":"Error: connect ETIMEDOUT\n    at errnoException (net.js:901:11)\n    at Object.afterConnect [as oncomplete] (net.js:892:19)","code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect"},"msg":"Calling metric_data on New Relic failed unexpectedly. Data will be held until it can be submitted:","time":"2014-09-08T00:36:02.989Z","v":0}
{"name":"newrelic","hostname":"simas","pid":8373,"level":30,"err":{"message":"connect ETIMEDOUT","name":"Error","stack":"Error: connect ETIMEDOUT\n    at errnoException (net.js:901:11)\n    at Object.afterConnect [as oncomplete] (net.js:892:19)","code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect"},"msg":"Error on submission to New Relic (data held for redelivery):","time":"2014-09-08T00:36:02.990Z","v":0}
